# Generated by Django 2.2.5 on 2020-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20201210_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='ATest', to='rooms.Amenity'),
        ),
    ]
